### ISSUE TITLE
recent changes broke LinuxKit tests

### ISSUE THREAD

**Issue by rn** [linuxkit/rtf#45]
rtf revision `c7b1f074f12ab2116509f69ffa6331aec104e244`
```
$ pwd
~/src/linuxkit/linuxkit/test
$ rtf list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a8 pc=0x10fa332]

goroutine 1 [running]:
github.com/linuxkit/rtf/local.(*Test).LabelString(0x0, 0x1, 0x1)
        /go/src/github.com/linuxkit/rtf/local/test.go:65 +0x22
github.com/linuxkit/rtf/cmd.list(0x165c880, 0x167f2c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/linuxkit/rtf/cmd/list.go:66 +0x47e
github.com/linuxkit/rtf/vendor/github.com/spf13/cobra.(*Command).execute(0x165c880, 0x167f2c0, 0x0, 0x0, 0x165c880, 0x167f2c0)
        /go/src/github.com/linuxkit/rtf/vendor/github.com/spf13/cobra/command.go:621 +0x3f8
github.com/linuxkit/rtf/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x165cac0, 0xc42006c058, 0x0, 0xc420109f48)
        /go/src/github.com/linuxkit/rtf/vendor/github.com/spf13/cobra/command.go:700 +0x339
github.com/linuxkit/rtf/vendor/github.com/spf13/cobra.(*Command).Execute(0x165cac0, 0x1, 0x1)
        /go/src/github.com/linuxkit/rtf/vendor/github.com/spf13/cobra/command.go:659 +0x2b
github.com/linuxkit/rtf/cmd.Execute()
        /go/src/github.com/linuxkit/rtf/cmd/root.go:42 +0x31
main.main()
        /go/src/github.com/linuxkit/rtf/main.go:20 +0x20
```

Probably one of my refactoring changes.

**Comment by rn** [comment]
The reason is that with `linuxkit.kernel.namespace` we skip a group and there for there is not `Test` object with labels associated with the result.

**Comment by ijc** [comment]
We need a tool to test this test framework :grinning:

**Comment by rn** [comment]
There are some unit tests...but coverage is not as good as it could be

**Comment by rn** [comment]
shoud be fixed via https://github.com/linuxkit/rtf/pull/47
